#Copyright(c) David Rueter All rights reserved. This program is made available under the
#terms of the AGPLv3 license. See the LICENSE file in the project root for more information.

version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SHEETS_SERVICE_ACCOUNT_CONFIG=${SHEETS_SERVICE_ACCOUNT_CONFIG}