# Copyright(c) David Rueter All rights reserved. This program is made available under the
# terms of the AGPLv3 license. See the LICENSE file in the project root for more information.

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
  labels:
    cloud.googleapis.com/location: europe-west1
  name: fffxmvp
  namespace: '146078851254'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '2'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 472.0.0
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: eksdsskemr
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 1
      containers:
      - env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              key: latest
              name: openai-api-key
        - name: SHEETS_SERVICE_ACCOUNT_CONFIG
          valueFrom:
            secretKeyRef:
              key: latest
              name: sheets-service-worker-key
        image: europe-west1-docker.pkg.dev/fffxmvp/fffxmvp-repo/fffxvmp:0.6
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      serviceAccountName: 146078851254-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100